"""PDF layer tests.

Every PDF here is generated by reportlab at test time: synthetic fixtures with
made-up text, not vendor documents. The image used for the raster-XObject test
is a 4x4 PNG built from zlib bytes in this file.
"""

from __future__ import annotations

import base64
import hashlib
import struct
import zlib
from pathlib import Path

import pytest
from pypdf import PdfWriter
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from boardmodeler.documents.pages import page_size_points, render_page_png
from boardmodeler.documents.pdf import (
    excerpt_on_page,
    normalize_for_citation,
    page_text,
    read_pdf,
)

# 4x4 solid red PNG, written with zlib so the fixtures need no imaging library.
_RED_PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAEElEQVR42mM4IScHRwzEcQCxYxBB00rMDQAAAABJRU5ErkJggg=="
)


def _write_text_pdf(path: Path) -> None:
    """Three pages: distinct markers, a hyphenated word split across lines."""
    sheet = canvas.Canvas(str(path), pagesize=letter)
    sheet.setTitle("Synthetic Datasheet Rev A")
    sheet.setAuthor("BoardModeler synthetic fixture")
    sheet.drawString(72, 700, "Page one alpha marker")
    sheet.showPage()
    sheet.drawString(72, 700, "Page two bravo marker")
    sheet.drawString(72, 680, "The word is configura-")
    sheet.drawString(72, 660, "tion split by hyphenation")
    sheet.showPage()
    sheet.drawString(72, 700, "Page three charlie marker")
    sheet.showPage()
    sheet.save()


def _write_vector_pdf(path: Path) -> None:
    """One page of pure vector art: content, but no text and no raster."""
    sheet = canvas.Canvas(str(path), pagesize=letter)
    sheet.rect(100, 100, 200, 200, stroke=1, fill=0)
    sheet.circle(300, 300, 50, stroke=1, fill=0)
    sheet.line(72, 72, 500, 700)
    sheet.showPage()
    sheet.save()


def _write_image_only_pdf(path: Path, image: Path) -> None:
    """One image page (no text) followed by one text page."""
    sheet = canvas.Canvas(str(path), pagesize=letter)
    sheet.drawImage(str(image), 72, 500, width=40, height=40)
    sheet.showPage()
    sheet.drawString(72, 700, "The only text in this file")
    sheet.showPage()
    sheet.save()


def _write_labeled_pdf(path: Path) -> None:
    """Two pages whose declared labels (i, ii) differ from their PDF indices."""
    sheet = canvas.Canvas(str(path), pagesize=letter)
    sheet.addPageLabel(0, style="ROMAN_LOWER", start=1)
    sheet.drawString(72, 700, "Cover")
    sheet.showPage()
    sheet.drawString(72, 700, "Body")
    sheet.showPage()
    sheet.save()


def _write_blank_second_page_pdf(path: Path) -> None:
    """One text page followed by a page with no content at all."""
    sheet = canvas.Canvas(str(path), pagesize=letter)
    sheet.drawString(72, 700, "Only content in the document")
    sheet.showPage()
    sheet.showPage()
    sheet.save()


def _write_large_page_pdf(path: Path, width: float, height: float) -> None:
    sheet = canvas.Canvas(str(path), pagesize=(width, height))
    sheet.drawString(10, 10, "poster")
    sheet.showPage()
    sheet.save()


def _write_red_page_pdf(path: Path) -> None:
    sheet = canvas.Canvas(str(path), pagesize=letter)
    sheet.setFillColorRGB(1, 0, 0)
    sheet.rect(0, 0, 612, 792, stroke=0, fill=1)
    sheet.showPage()
    sheet.save()


def _png_header_and_first_pixel(data: bytes) -> tuple[int, int, tuple[int, int, int]]:
    """Decode an 8-bit RGB PNG far enough to read its size and first pixel."""
    assert data[:8] == b"\x89PNG\r\n\x1a\n", "not a PNG"
    offset = 8
    header = b""
    idat = b""
    while offset < len(data):
        length = int.from_bytes(data[offset : offset + 4], "big")
        tag = data[offset + 4 : offset + 8]
        payload = data[offset + 8 : offset + 8 + length]
        if tag == b"IHDR":
            header = payload
        elif tag == b"IDAT":
            idat += payload
        offset += 12 + length
    width, height, depth, color_type = struct.unpack(">IIBB", header[:10])
    assert depth == 8 and color_type == 2, f"unexpected depth/colour type: {depth}/{color_type}"
    scanlines = zlib.decompress(idat)
    assert scanlines[0] == 0, "first scanline is expected to be unfiltered"
    return width, height, tuple(scanlines[1:4])


# --------------------------------------------------------------------------- #
# reading


def test_reads_page_count_title_and_hash(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)

    document = read_pdf(source)

    assert document.page_count == 3
    assert len(document.pages) == 3
    assert [page.pdf_page for page in document.pages] == [0, 1, 2]
    assert document.title == "Synthetic Datasheet Rev A"
    assert document.metadata["Author"] == "BoardModeler synthetic fixture"
    assert document.text_extraction == "embedded"


def test_file_hash_is_the_hash_of_the_bytes(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)

    document = read_pdf(source)

    assert document.file_hash == hashlib.sha256(source.read_bytes()).hexdigest()


def test_page_text_is_scoped_to_its_own_page(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)

    document = read_pdf(source)

    assert "bravo marker" in page_text(document, 1)
    assert "bravo marker" not in page_text(document, 0)
    assert "alpha marker" in page_text(document, 0)
    assert document.pages[1].char_count == len(page_text(document, 1))
    assert document.pages[1].has_embedded_text is True


def test_page_text_rejects_an_out_of_range_page(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)
    document = read_pdf(source)

    with pytest.raises(IndexError):
        page_text(document, 3)
    with pytest.raises(IndexError):
        page_text(document, -1)


def test_max_pages_limits_the_read_pages_but_not_the_page_count(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)

    document = read_pdf(source, max_pages=2)

    assert document.page_count == 3
    assert [page.pdf_page for page in document.pages] == [0, 1]
    with pytest.raises(IndexError):
        page_text(document, 2)


def test_max_pages_must_be_positive(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)

    with pytest.raises(ValueError):
        read_pdf(source, max_pages=0)


def test_vector_only_pdf_reports_no_text(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_vector.pdf"
    _write_vector_pdf(source)

    document = read_pdf(source)

    assert document.text_extraction == "none"
    assert document.pages[0].has_embedded_text is False
    assert document.pages[0].char_count == 0
    assert document.pages[0].images == 0


def test_image_only_page_is_hybrid_and_never_upgraded(tmp_path: Path) -> None:
    image = tmp_path / "pixel.png"
    image.write_bytes(_RED_PNG)
    source = tmp_path / "synthetic_scanned.pdf"
    _write_image_only_pdf(source, image)

    document = read_pdf(source)

    assert document.pages[0].images == 1
    assert document.pages[0].has_embedded_text is False
    assert document.pages[1].has_embedded_text is True
    assert document.text_extraction == "hybrid"
    assert excerpt_on_page(document, "The only text in this file", 1) is True


def test_blank_page_does_not_downgrade_embedded_text(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_blank_page.pdf"
    _write_blank_second_page_pdf(source)

    document = read_pdf(source)

    assert document.page_count == 2
    assert document.pages[1].has_embedded_text is False
    assert document.pages[1].images == 0
    assert document.text_extraction == "embedded"


def test_page_labels_come_from_the_declared_label_tree(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_labeled.pdf"
    _write_labeled_pdf(source)

    document = read_pdf(source)

    assert document.page_labels == {0: "i", 1: "ii"}
    assert document.pages[0].printed_label == "i"


def test_page_labels_stay_absent_when_the_document_declares_none(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)

    document = read_pdf(source)

    # pypdf synthesises "1", "2", "3" here; those are viewer defaults, not the
    # numbers the document prints, so no label may be reported.
    assert document.page_labels == {}
    assert document.pages[1].printed_label is None


# --------------------------------------------------------------------------- #
# citation matching


def test_excerpt_is_found_on_a_page_and_rejected_on_another(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)
    document = read_pdf(source)

    assert excerpt_on_page(document, "Page two bravo marker", 1) is True
    assert excerpt_on_page(document, "Page two bravo marker", 0) is False
    assert excerpt_on_page(document, "Page three charlie marker", 2) is True


def test_excerpt_survives_line_break_and_hyphenation(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)
    document = read_pdf(source)

    # The page really contains "configura-\ntion"; the citation is the word.
    assert "configura-" in page_text(document, 1)
    assert "configuration" not in page_text(document, 1)
    assert excerpt_on_page(document, "configuration split by hyphenation", 1) is True
    # The reverse direction: the citation keeps the printed break.
    assert excerpt_on_page(document, "The word is configura-\ntion", 1) is True
    # A citation broken across a line without hyphenation still matches.
    assert excerpt_on_page(document, "bravo marker The word", 1) is True


def test_invented_excerpt_is_rejected(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)
    document = read_pdf(source)

    invented = "The device survives a 42 V transient for 10 ms"
    for page in range(document.page_count):
        assert excerpt_on_page(document, invented, page) is False
    assert excerpt_on_page(document, "", 1) is False
    assert excerpt_on_page(document, "   \n\t ", 1) is False


def test_excerpt_compares_only_the_first_max_chars(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)
    document = read_pdf(source)

    # The page contains the marker but none of the fabricated tail, so the full
    # excerpt must be rejected and only the first 21 characters may be compared.
    excerpt = "Page two bravo marker " + "x" * 400
    assert excerpt_on_page(document, excerpt, 1) is False
    assert excerpt_on_page(document, excerpt, 1, max_chars=21) is True
    invented_prefix = "y" * 400 + " Page two bravo marker"
    assert excerpt_on_page(document, invented_prefix, 1) is False
    with pytest.raises(ValueError):
        excerpt_on_page(document, "Page two bravo marker", 1, max_chars=0)


def test_normalize_for_citation_collapses_whitespace_and_typography() -> None:
    collapsed = normalize_for_citation("  Output\tvoltage\n\n rises   slowly ")
    assert collapsed == "Output voltage rises slowly"

    assert normalize_for_citation("3\u20135 V \u2013 5\u22126 V") == "3-5 V - 5-6 V"
    assert normalize_for_citation("\u201cconfiguration\u201d") == '"configuration"'
    assert normalize_for_citation("don\u2019t") == "don't"
    assert normalize_for_citation("con\ufb01guration \ufb02ow") == "configuration flow"
    assert normalize_for_citation("soft\u00adhyphen") == "softhyphen"
    assert normalize_for_citation("\u00a0") == ""


# --------------------------------------------------------------------------- #
# rasterization (documents/pages.py)


def test_page_size_points_matches_the_page_geometry(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)
    document = read_pdf(source)

    assert page_size_points(document, 0) == (612.0, 792.0)


def test_render_page_png_produces_a_png_of_the_requested_size(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_red.pdf"
    _write_red_page_pdf(source)
    document = read_pdf(source)

    at_one = render_page_png(document, 0, scale=1.0)
    width, height, first_pixel = _png_header_and_first_pixel(at_one)
    assert (width, height) == (612, 792)
    # Byte order matters: a red fill must decode as red, not blue.
    assert first_pixel == (255, 0, 0)

    at_half = render_page_png(document, 0, scale=0.5)
    assert _png_header_and_first_pixel(at_half)[:2] == (306, 396)


def test_render_page_png_refuses_a_render_over_the_pixel_budget(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_poster.pdf"
    _write_large_page_pdf(source, 20_000, 20_000)
    document = read_pdf(source)

    with pytest.raises(ValueError) as excinfo:
        render_page_png(document, 0, scale=2.0, max_pixels=40_000_000)

    message = str(excinfo.value)
    assert "20000.0x20000.0 pt" in message
    assert "40000x40000" in message
    assert "max_pixels=40000000" in message
    # The same page renders when the caller asks for fewer pixels.
    assert render_page_png(document, 0, scale=0.01).startswith(b"\x89PNG\r\n\x1a\n")


def test_render_page_png_rejects_an_out_of_range_page(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)
    document = read_pdf(source)

    with pytest.raises(IndexError):
        render_page_png(document, 3)
    with pytest.raises(ValueError):
        render_page_png(document, 0, scale=0.0)


def test_rotated_page_is_measured_and_rendered_as_displayed(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_datasheet.pdf"
    _write_text_pdf(source)
    rotated = tmp_path / "synthetic_rotated.pdf"
    writer = PdfWriter()
    writer.append(str(source))
    writer.pages[0].rotate(90)
    with rotated.open("wb") as handle:
        writer.write(handle)

    document = read_pdf(rotated)

    assert page_size_points(document, 0) == (792.0, 612.0)
    width, height, _ = _png_header_and_first_pixel(render_page_png(document, 0, scale=1.0))
    assert (width, height) == (792, 612)


def test_a_pypdf_internal_fault_falls_back_to_pdfium(tmp_path, monkeypatch):
    """pypdf raised ``NameError: _LENGTH_LIMIT`` on a readable datasheet (1 of 4 runs).

    Before the fallback that one fault stopped the whole build at "read"; now the same
    pages, text and image counts come from pdfium and the build continues.
    """
    import boardmodeler.documents.pdf as pdf_module

    image = tmp_path / "red.png"
    image.write_bytes(_RED_PNG)
    source = tmp_path / "mixed.pdf"
    _write_image_only_pdf(source, image)
    expected = read_pdf(source)

    def broken_reader(*_args, **_kwargs):
        raise NameError("name '_LENGTH_LIMIT' is not defined")

    monkeypatch.setattr(pdf_module, "PdfReader", broken_reader)
    doc = read_pdf(source)
    assert doc.page_count == expected.page_count == 2
    assert "The only text in this file" in page_text(doc, 1)
    assert [page.images for page in doc.pages] == [page.images for page in expected.pages]
    assert doc.text_extraction == expected.text_extraction == "hybrid"
    assert doc.page_labels == {}  # a label is reported only when the document's tree was read


def test_an_unreadable_file_still_raises_pypdfs_error(tmp_path):
    bad = tmp_path / "bad.pdf"
    bad.write_bytes(b"not a pdf at all")
    with pytest.raises(Exception) as caught:
        read_pdf(bad)
    assert "pypdf" in type(caught.value).__module__
