"""Source-consistency tests for ``requirements/review.py`` (Plan Phase 2 §3).

The PDFs used here are generated by reportlab at test time: two pages of
synthetic text written for this file. They are not vendor documents and no
excerpt below is presented as coming from one.

The point of these tests is the product's central claim: a citation counts as
verified only when the excerpt really appears on the cited page of the cited
document — a document that exists, a page that exists, and an excerpt that is
"close enough" all fail.
"""

from __future__ import annotations

from dataclasses import FrozenInstanceError
from pathlib import Path
from typing import Any

import pytest
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from boardmodeler.documents.pdf import PdfDocument, page_text, read_pdf
from boardmodeler.domain.enums import (
    Criticality,
    EvidenceExtraction,
    RequirementClass,
    RequirementKind,
    RequirementOrigin,
)
from boardmodeler.domain.records import (
    Condition,
    DocumentRecord,
    EvidenceRef,
    Limit,
    PageRef,
    Requirement,
)
from boardmodeler.requirements import review as review_module
from boardmodeler.requirements.review import (
    ReviewOutcome,
    apply_review,
    find_conflicts,
    review,
    verify_citations,
)

DOC_ID = "DOC_synthetic_review"
SECOND_DOC_ID = "DOC_synthetic_review_rev_b"
PAGE_ONE_TEXT = "Reference voltage is 0.795 V typical."
PAGE_TWO_TEXT = "Page two carries only this sentence."
EXCERPT_ON_PAGE_ONE = "Reference voltage is 0.795 V"
INVENTED_EXCERPT = "This sentence was never printed anywhere."
DEFAULT_LIMITS = {"min": 0.788, "typ": 0.795, "max": 0.802, "unit": "V"}


def _write_two_page_pdf(path: Path) -> None:
    """Two synthetic pages with distinct, made-up markers."""
    sheet = canvas.Canvas(str(path), pagesize=letter)
    sheet.setTitle("Synthetic review datasheet")
    sheet.drawString(72, 700, PAGE_ONE_TEXT)
    sheet.showPage()
    sheet.drawString(72, 700, PAGE_TWO_TEXT)
    sheet.showPage()
    sheet.save()


@pytest.fixture
def pdf(tmp_path: Path) -> Path:
    path = tmp_path / "synthetic_review.pdf"
    _write_two_page_pdf(path)
    return path


def make_document(
    path: str,
    *,
    doc_id: str = DOC_ID,
    page_count: int = 2,
    text_extraction: str = "embedded",
) -> DocumentRecord:
    return DocumentRecord(
        doc_id=doc_id,
        title="Synthetic review datasheet",
        doc_type="datasheet",
        provenance="synthetic_fixture",
        file_hash="1" * 64,
        page_count=page_count,
        text_extraction=text_extraction,
        path=path,
    )


def make_requirement(
    req_id: str = "REQ_SYNTH_ELEC_001",
    *,
    origin: RequirementOrigin = RequirementOrigin.DOCUMENT,
    criticality: Criticality = Criticality.CRITICAL,
    statement: str = "The 3V3 output stays within its regulation limits.",
    excerpt: str = EXCERPT_ON_PAGE_ONE,
    section: str | None = "Electrical Characteristics",
    doc_id: str = DOC_ID,
    page: int | None = 0,
    limits: dict[str, Any] | None = DEFAULT_LIMITS,
    expression: dict[str, Any] | None = None,
    conditions: list[dict[str, Any]] | None = None,
    signal_refs: list[str] | None = None,
    applies_to: str = "U1",
    configuration: str | None = None,
    citation_verified: bool = False,
    status: str = "active",
) -> Requirement:
    evidence = []
    if page is not None or origin is RequirementOrigin.DOCUMENT:
        evidence = [
            EvidenceRef(
                doc_id=doc_id,
                page=None if page is None else PageRef(pdf_page=page),
                section=section,
                excerpt=excerpt,
                extraction=EvidenceExtraction.SYNTHETIC_FIXTURE
                if origin is RequirementOrigin.TEST_FIXTURE
                else EvidenceExtraction.EMBEDDED_TEXT,
            )
        ]
    return Requirement(
        req_id=req_id,
        applies_to=applies_to,
        configuration=configuration,
        kind=RequirementKind.ELECTRICAL,
        **{
            "class": RequirementClass.DOCUMENTED_LIMIT,
            "criticality": criticality,
            "origin": origin,
            "statement": statement,
            "limits": limit(limits),
            "expression": expression,
            "conditions": [Condition(**condition) for condition in conditions or []],
            "signal_refs": signal_refs or [],
            "evidence": evidence,
            "citation_verified": citation_verified,
            "status": status,
        },
    )


def limit(values: dict[str, Any] | None) -> Limit | None:
    return None if values is None else Limit(**values)


# --------------------------------------------------------------------------- #
# citation verification


def test_citation_found_on_the_cited_page_verifies(pdf: Path) -> None:
    requirement = make_requirement()
    documents = {DOC_ID: make_document(str(pdf))}

    assert verify_citations([requirement], documents) == {requirement.req_id: True}

    outcome = review([requirement], documents)

    assert outcome.verified == [requirement.req_id]
    assert outcome.unverified == []
    assert outcome.coverage == 1.0
    assert outcome.items == []
    assert outcome.issues == []


def test_citation_on_the_wrong_page_does_not_verify(pdf: Path) -> None:
    requirement = make_requirement(page=1)
    documents = {DOC_ID: make_document(str(pdf))}

    assert verify_citations([requirement], documents) == {requirement.req_id: False}

    outcome = review([requirement], documents)

    assert outcome.unverified == [requirement.req_id]
    assert outcome.verified == []
    assert outcome.coverage == 0.0
    assert [issue.code for issue in outcome.issues] == ["citation_excerpt_not_found"]
    assert [item.kind for item in outcome.items] == ["missing_evidence"]
    assert outcome.items[0].id == f"RV_citation_{requirement.req_id}"
    assert outcome.items[0].options == [
        "accept as UNKNOWN",
        "supply the correct page",
        "reject the requirement",
    ]


def test_invented_excerpt_does_not_verify(pdf: Path) -> None:
    requirement = make_requirement(excerpt=INVENTED_EXCERPT)
    documents = {DOC_ID: make_document(str(pdf))}

    assert verify_citations([requirement], documents) == {requirement.req_id: False}

    outcome = review([requirement], documents)

    assert "citation_excerpt_not_found" in [issue.code for issue in outcome.issues]
    assert outcome.items[0].kind == "missing_evidence"


def test_document_without_extractable_text_is_unverifiable(pdf: Path) -> None:
    requirement = make_requirement()
    documents = {DOC_ID: make_document(str(pdf), text_extraction="none")}

    # The excerpt really is on page one of the file, but the record says the
    # document has no extracted text, so nothing may be claimed from it.
    assert verify_citations([requirement], documents) == {requirement.req_id: False}

    outcome = review([requirement], documents)

    assert [issue.code for issue in outcome.issues] == ["citation_unverifiable_no_text"]
    assert outcome.items[0].kind == "missing_evidence"


def test_citation_to_a_page_outside_the_document_is_unverified(pdf: Path) -> None:
    requirement = make_requirement(page=5)
    documents = {DOC_ID: make_document(str(pdf))}

    assert verify_citations([requirement], documents) == {requirement.req_id: False}

    outcome = review([requirement], documents)

    assert "citation_page_out_of_range" in [issue.code for issue in outcome.issues]
    assert outcome.items[0].kind == "missing_evidence"


def test_empty_excerpt_is_unverified(pdf: Path) -> None:
    requirement = make_requirement(excerpt="   ")
    documents = {DOC_ID: make_document(str(pdf))}

    assert verify_citations([requirement], documents) == {requirement.req_id: False}
    assert [i.code for i in review([requirement], documents).issues if "excerpt" in i.code] == [
        "citation_excerpt_empty"
    ]


def test_unknown_document_id_is_unverified() -> None:
    requirement = make_requirement(doc_id="DOC_never_stored")

    assert verify_citations([requirement], {}) == {requirement.req_id: False}

    outcome = review([requirement], {})

    assert [issue.code for issue in outcome.issues] == ["citation_doc_unknown"]
    assert outcome.items[0].kind == "missing_evidence"


def test_blank_document_id_is_unverified() -> None:
    requirement = make_requirement(doc_id="")

    assert verify_citations([requirement], {}) == {requirement.req_id: False}

    outcome = review([requirement], {})

    assert [issue.code for issue in outcome.issues] == ["citation_doc_unknown"]
    assert outcome.items[0].kind == "missing_evidence"


def test_unreadable_document_is_unverified_not_a_crash() -> None:
    requirement = make_requirement()
    documents = {DOC_ID: make_document("")}

    assert verify_citations([requirement], documents) == {requirement.req_id: False}

    outcome = review([requirement], documents)

    assert [issue.code for issue in outcome.issues] == ["citation_source_unreadable"]
    assert requirement.req_id in outcome.unverified


def test_excerpt_lookup_is_used_instead_of_the_document_file() -> None:
    requirement = make_requirement()
    documents = {DOC_ID: make_document("")}  # no file on disk: the lookup must be enough
    pages = {(DOC_ID, 0): PAGE_ONE_TEXT}

    def lookup(doc_id: str, page: int) -> str | None:
        return pages.get((doc_id, page))

    def missing(doc_id: str, page: int) -> str | None:
        return None

    assert verify_citations([requirement], documents, excerpt_lookup=lookup) == {
        requirement.req_id: True
    }
    assert verify_citations([requirement], documents, excerpt_lookup=missing) == {
        requirement.req_id: False
    }


def test_excerpt_lookup_and_the_pdf_path_agree(pdf: Path) -> None:
    requirement = make_requirement()
    documents = {DOC_ID: make_document(str(pdf))}
    parsed: PdfDocument = read_pdf(pdf)

    def lookup(doc_id: str, page: int) -> str | None:
        return page_text(parsed, page)

    assert verify_citations([requirement], documents) == verify_citations(
        [requirement], documents, excerpt_lookup=lookup
    )


def test_the_pdf_is_read_once_per_call(pdf: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    reads: list[tuple[str, int | None]] = []
    real_read_pdf = review_module.read_pdf

    def counting_read_pdf(path: str | Path, *, max_pages: int | None = None) -> PdfDocument:
        reads.append((str(path), max_pages))
        return real_read_pdf(path, max_pages=max_pages)

    monkeypatch.setattr(review_module, "read_pdf", counting_read_pdf)
    requirements = [make_requirement(req_id="REQ_A"), make_requirement(req_id="REQ_B", page=1)]
    documents = {DOC_ID: make_document(str(pdf))}

    outcome = review(requirements, documents)

    assert outcome.verified == ["REQ_A"]
    assert outcome.unverified == ["REQ_B"]
    # One read, and only the pages that are cited.
    assert reads == [(str(pdf), 2)]


# --------------------------------------------------------------------------- #
# origins that are not documents


def test_test_fixture_requirements_are_not_citation_verified() -> None:
    requirement = make_requirement(
        req_id="REQ_FIXTURE_CONNECTIVITY",
        origin=RequirementOrigin.TEST_FIXTURE,
        doc_id="DOC_switch_fixture",
        page=None,
        excerpt="The synthetic contract declares this strap.",
    )

    assert verify_citations([requirement], {}) == {}

    outcome = review([requirement], {})

    assert outcome.verified == []
    assert outcome.unverified == []
    assert outcome.coverage == 0.0
    assert outcome.items == []


def test_user_requirements_are_not_citation_verified() -> None:
    requirement = make_requirement(
        req_id="REQ_USER_SEQUENCING",
        origin=RequirementOrigin.USER,
        statement="The 1V8 rail must come up after the 3V3 rail.",
        page=1,  # would fail verification if it were treated as document data
        limits=None,
    )

    outcome = review([requirement], {})

    assert outcome.verified == []
    assert outcome.unverified == []
    assert outcome.coverage == 0.0


def test_coverage_counts_only_verifiable_requirements(pdf: Path) -> None:
    good = make_requirement(req_id="REQ_GOOD")
    bad = make_requirement(req_id="REQ_BAD", page=1)
    fixture = make_requirement(
        req_id="REQ_FIXTURE", origin=RequirementOrigin.TEST_FIXTURE, page=None
    )
    documents = {DOC_ID: make_document(str(pdf))}

    outcome = review([good, bad, fixture], documents)

    assert outcome.verified == ["REQ_GOOD"]
    assert outcome.unverified == ["REQ_BAD"]
    assert outcome.coverage == 0.5


def test_coverage_is_zero_when_nothing_can_be_verified() -> None:
    fixture = make_requirement(
        req_id="REQ_FIXTURE", origin=RequirementOrigin.TEST_FIXTURE, page=None
    )

    outcome = review([fixture], {})

    assert outcome.coverage == 0.0
    assert outcome.verified == []
    assert outcome.unverified == []


# --------------------------------------------------------------------------- #
# conflicts


def test_disjoint_limits_conflict_and_are_preserved(pdf: Path) -> None:
    high = make_requirement(
        req_id="REQ_MAX_3366",
        limits={"max": 3.366, "unit": "V"},
        expression={"op": "le", "signal": "V(VOUT)", "value": 3.366, "unit": "V"},
        signal_refs=["V(VOUT)"],
    )
    low = make_requirement(
        req_id="REQ_MIN_3500",
        limits={"min": 3.5, "unit": "V"},
        expression={"op": "ge", "signal": "V(VOUT)", "value": 3.5, "unit": "V"},
        signal_refs=["V(VOUT)"],
    )
    documents = {DOC_ID: make_document(str(pdf))}

    pairs = find_conflicts([high, low])

    assert len(pairs) == 1
    first, second, reason = pairs[0]
    assert (first, second) == ("REQ_MAX_3366", "REQ_MIN_3500")
    assert "3.366" in reason and "3.5" in reason

    outcome = review([high, low], documents)

    assert outcome.conflicts == ["REQ_MAX_3366", "REQ_MIN_3500"]
    assert [item.kind for item in outcome.items] == ["conflict"]
    assert outcome.items[0].blocking is True
    assert outcome.items[0].id == "RV_conflict_REQ_MAX_3366__REQ_MIN_3500"
    assert outcome.items[0].affected_requirement_ids == ["REQ_MAX_3366", "REQ_MIN_3500"]

    applied = {
        requirement.req_id: requirement for requirement in apply_review([high, low], outcome)
    }

    assert applied["REQ_MAX_3366"].status == "conflict"
    assert applied["REQ_MIN_3500"].status == "conflict"
    assert applied["REQ_MAX_3366"].conflicts == [f"REQ_MIN_3500: {reason}"]
    assert applied["REQ_MIN_3500"].conflicts == [f"REQ_MAX_3366: {reason}"]


def test_overlapping_or_touching_limits_do_not_conflict() -> None:
    overlapping = [
        make_requirement(req_id="REQ_A", limits={"max": 3.4, "unit": "V"}),
        make_requirement(req_id="REQ_B", limits={"min": 3.3, "unit": "V"}),
    ]
    touching = [
        make_requirement(req_id="REQ_A2", limits={"max": 3.366, "unit": "V"}),
        make_requirement(req_id="REQ_B2", limits={"min": 3.366, "unit": "V"}),
    ]

    assert find_conflicts(overlapping) == []
    assert find_conflicts(touching) == []


def test_conflict_requires_the_same_signal() -> None:
    on_vout = make_requirement(
        req_id="REQ_VOUT",
        limits={"max": 3.366, "unit": "V"},
        expression={"op": "le", "signal": "V(VOUT)", "value": 3.366, "unit": "V"},
    )
    on_vin = make_requirement(
        req_id="REQ_VIN",
        limits={"min": 3.5, "unit": "V"},
        expression={"op": "ge", "signal": "V(VIN)", "value": 3.5, "unit": "V"},
    )

    assert find_conflicts([on_vout, on_vin]) == []


def test_conflict_requires_the_same_configuration_and_applies_to() -> None:
    other_configuration = [
        make_requirement(req_id="REQ_A", limits={"max": 3.366, "unit": "V"}, configuration="3V3"),
        make_requirement(req_id="REQ_B", limits={"min": 3.5, "unit": "V"}, configuration="1V8"),
    ]
    other_part = [
        make_requirement(req_id="REQ_C", limits={"max": 3.366, "unit": "V"}, applies_to="U1"),
        make_requirement(req_id="REQ_D", limits={"min": 3.5, "unit": "V"}, applies_to="U2"),
    ]

    assert find_conflicts(other_configuration) == []
    assert find_conflicts(other_part) == []


def test_conflict_detection_converts_si_prefixes() -> None:
    millivolts = make_requirement(req_id="REQ_MV", limits={"max": 3366, "unit": "mV"})
    volts = make_requirement(req_id="REQ_V", limits={"min": 3.5, "unit": "V"})

    pairs = find_conflicts([millivolts, volts])

    assert [pair[:2] for pair in pairs] == [("REQ_MV", "REQ_V")]
    assert "3.366 V" in pairs[0][2]


def test_expression_bounds_are_used_when_no_limit_triple_exists() -> None:
    upper = make_requirement(
        req_id="REQ_EXPR_MAX",
        limits=None,
        expression={"op": "lt", "signal": "V(VOUT)", "value": 3.366, "unit": "V"},
        signal_refs=["V(VOUT)"],
    )
    lower = make_requirement(
        req_id="REQ_EXPR_MIN",
        limits=None,
        expression={"op": "gt", "signal": "V(VOUT)", "value": 3.5, "unit": "V"},
        signal_refs=["V(VOUT)"],
    )

    assert [pair[:2] for pair in find_conflicts([upper, lower])] == [
        ("REQ_EXPR_MAX", "REQ_EXPR_MIN")
    ]


def test_conditional_and_disjunctive_expressions_are_not_intervals() -> None:
    upper = make_requirement(
        req_id="REQ_ANY_MAX",
        limits=None,
        expression={
            "op": "any_of",
            "items": [{"op": "lt", "signal": "V(VOUT)", "value": 3.366, "unit": "V"}],
        },
        signal_refs=["V(VOUT)"],
    )
    lower = make_requirement(
        req_id="REQ_ANY_MIN",
        limits=None,
        expression={"op": "gt", "signal": "V(VOUT)", "value": 3.5, "unit": "V"},
        signal_refs=["V(VOUT)"],
    )

    assert find_conflicts([upper, lower]) == []


def test_the_same_statement_from_different_documents_with_different_values_conflicts() -> None:
    statement = "The output voltage must not exceed the regulation limit."
    first = make_requirement(
        req_id="REQ_REV_A",
        doc_id="DOC_rev_a",
        statement=statement,
        limits={"max": 3.366, "unit": "V"},
    )
    second = make_requirement(
        req_id="REQ_REV_B",
        doc_id=SECOND_DOC_ID,
        statement=statement,
        limits={"max": 3.5, "unit": "V"},
    )

    pairs = find_conflicts([first, second])

    assert len(pairs) == 1
    first_id, second_id, reason = pairs[0]
    assert (first_id, second_id) == ("REQ_REV_A", "REQ_REV_B")
    assert "different values" in reason
    assert "DOC_rev_a" in reason and SECOND_DOC_ID in reason


def test_identical_statements_with_equal_values_or_one_document_do_not_conflict() -> None:
    equal_values = [
        make_requirement(req_id="REQ_A", doc_id="DOC_rev_a", limits={"max": 3.366, "unit": "V"}),
        make_requirement(req_id="REQ_B", doc_id=SECOND_DOC_ID, limits={"max": 3.366, "unit": "V"}),
    ]
    one_document = [
        make_requirement(req_id="REQ_C", doc_id="DOC_rev_a", limits={"max": 3.366, "unit": "V"}),
        make_requirement(req_id="REQ_D", doc_id="DOC_rev_a", limits={"max": 3.5, "unit": "V"}),
    ]

    assert find_conflicts(equal_values) == []
    assert find_conflicts(one_document) == []


def test_superseded_requirements_are_not_compared() -> None:
    withdrawn = make_requirement(
        req_id="REQ_OLD", limits={"max": 3.366, "unit": "V"}, status="superseded"
    )
    current = make_requirement(req_id="REQ_NEW", limits={"min": 3.5, "unit": "V"})

    assert find_conflicts([withdrawn, current]) == []


# --------------------------------------------------------------------------- #
# apply_review


def test_apply_review_sets_citation_verified_and_keeps_the_expression(pdf: Path) -> None:
    verified = make_requirement(
        req_id="REQ_GOOD",
        expression={"op": "le", "signal": "V(VOUT)", "value": 0.802, "unit": "V"},
        signal_refs=["V(VOUT)"],
    )
    unverified = make_requirement(
        req_id="REQ_BAD",
        page=1,
        citation_verified=True,  # a stale claim the review has to overwrite
        expression={"op": "ge", "signal": "V(FB)", "value": 0.788, "unit": "V"},
        signal_refs=["V(FB)"],
    )
    fixture = make_requirement(
        req_id="REQ_FIXTURE", origin=RequirementOrigin.TEST_FIXTURE, page=None
    )
    documents = {DOC_ID: make_document(str(pdf))}

    outcome = review([verified, unverified, fixture], documents)
    applied = {
        requirement.req_id: requirement
        for requirement in apply_review([verified, unverified, fixture], outcome)
    }

    assert applied["REQ_GOOD"].citation_verified is True
    assert applied["REQ_BAD"].citation_verified is False
    assert applied["REQ_BAD"].expression is not None
    assert applied["REQ_FIXTURE"].citation_verified is False
    assert applied["REQ_FIXTURE"].status == "active"


def test_apply_review_is_idempotent(pdf: Path) -> None:
    high = make_requirement(req_id="REQ_HIGH", limits={"max": 3.366, "unit": "V"})
    low = make_requirement(req_id="REQ_LOW", limits={"min": 3.5, "unit": "V"})
    documents = {DOC_ID: make_document(str(pdf))}

    outcome = review([high, low], documents)
    once = apply_review([high, low], outcome)
    twice = apply_review(once, outcome)

    assert [requirement.model_dump() for requirement in once] == [
        requirement.model_dump() for requirement in twice
    ]


# --------------------------------------------------------------------------- #
# items, blocking and determinism


def test_only_critical_unverifiable_requirements_block(pdf: Path) -> None:
    critical = make_requirement(req_id="REQ_CRIT", page=1, criticality=Criticality.CRITICAL)
    important = make_requirement(req_id="REQ_IMPORTANT", page=1, criticality=Criticality.IMPORTANT)
    documents = {DOC_ID: make_document(str(pdf))}

    outcome = review([critical, important], documents)

    blocking = {item.id: item.blocking for item in outcome.items}

    assert blocking == {
        "RV_citation_REQ_CRIT": True,
        "RV_citation_REQ_IMPORTANT": False,
    }


def test_ambiguity_items_only_cover_critical_requirements() -> None:
    excerpt = "Reference voltage is 0.795 V, TA = 25 C."
    critical = make_requirement(req_id="REQ_CRIT", excerpt=excerpt)
    informational = make_requirement(
        req_id="REQ_INFO", excerpt=excerpt, criticality=Criticality.INFORMATIONAL
    )

    outcome = review([critical, informational], {})

    ambiguity = [item for item in outcome.items if item.kind == "ambiguity"]

    assert [item.id for item in ambiguity] == ["RV_ambiguity_REQ_CRIT_conditions_missing"]
    assert ambiguity[0].blocking is False
    assert "conditions_missing" in [issue.code for issue in outcome.issues]


def test_review_is_deterministic(pdf: Path) -> None:
    requirements = [
        make_requirement(req_id="REQ_GOOD"),
        make_requirement(req_id="REQ_BAD", page=1),
        make_requirement(req_id="REQ_HIGH", limits={"max": 3.366, "unit": "V"}),
        make_requirement(req_id="REQ_LOW", limits={"min": 3.5, "unit": "V"}),
        make_requirement(
            req_id="REQ_AMBIGUOUS", excerpt="Reference voltage is 0.795 V, TA = 25 C."
        ),
    ]
    documents = {DOC_ID: make_document(str(pdf))}

    first = review(requirements, documents)
    second = review(requirements, documents)

    assert first.verified == second.verified
    assert first.unverified == second.unverified
    assert first.conflicts == second.conflicts
    assert first.issues == second.issues
    assert [item.model_dump() for item in first.items] == [
        item.model_dump() for item in second.items
    ]
    assert len(first.items) >= 4
    assert {item.kind for item in first.items} == {"missing_evidence", "conflict", "ambiguity"}


def test_review_outcome_is_frozen() -> None:
    outcome = ReviewOutcome(verified=[], unverified=[], conflicts=[], items=[], issues=[])

    with pytest.raises(FrozenInstanceError):
        outcome.coverage = 1.0  # type: ignore[misc]


def test_an_excerpt_verifies_when_any_one_reading_of_the_page_contains_it() -> None:
    from boardmodeler.requirements.review import READING_BREAK, _excerpt_in

    spaced = "Input offset voltage VS = 5 V; V C M = 0 V; V O = 1.4 V"
    tight = "Input offset voltage VS = 5 V; VC M = 0 V; VO = 1.4 V"
    excerpt = "Input offset voltage VS = 5 V; VC M = 0 V; VO = 1.4 V"
    assert not _excerpt_in(spaced, excerpt)
    assert _excerpt_in(spaced + READING_BREAK + tight, excerpt)
    assert _excerpt_in(tight + READING_BREAK + spaced, excerpt)


def test_an_excerpt_is_never_matched_across_the_break_between_two_readings() -> None:
    from boardmodeler.requirements.review import READING_BREAK, _excerpt_in

    assert not _excerpt_in("alpha beta" + READING_BREAK + "gamma delta", "beta gamma")
    assert not _excerpt_in("", "beta") and not _excerpt_in(READING_BREAK, "beta")
